// This file has been automatically generated by getSvnRevision.bat 
// $Id: HopsanCoreSVNRevision.h 9154M 2016-10-13 07:43:42Z (local) $ 
#ifndef HOPSANCORESVNREVISION_H_INCLUDED 
#define HOPSANCORESVNREVISION_H_INCLUDED 
#define HOPSANCORESVNREVISION 9154  
#endif 
